### PR TITLE
-fixed problem with wrong visualization of card in web

### PR DESCRIPTION
**Pull request by AyoPrez**
This pull request solves the issue #14

### CODE REVIEW

**Comment by diegogarciar** [comment]
Hello, thank you for submitting this PR.  I think you accidentally included the spanish translation, is it ok if you remove that commit? Otherwise I can commit the fix separately without this PR.

**Comment by AyoPrez** [comment]
> Hello, thank you for submitting this PR. I think you accidentally included the spanish translation, is it ok if you remove that commit? Otherwise I can commit the fix separately without this PR.

Hi. Thank for your message. This was long ago but I think it was not accidentally. I thought that wouldn't be bad to have other languages. But if you prefer that the translations are not included I (or you) can remove that commit without any problem.

**Comment by diegogarciar** [comment]
Yes I just volunteered to help with the package. I can do the commit easier as your branch is already outdated, thanks for the help!

**Comment by diegogarciar** [comment]
Can you just confirm that this doesn't break mobile?

**Comment by AyoPrez** [comment]
In the time I did it , no, it was not breaking mobile. I haven't used this library in a while.

**Pull request closed without merging**
